// src/routes/contact.svelte
<script>
    import SocialIcons from "../components/SocialIcons.svelte";
</script>

<svelte:head>
    <title>Contact - Alamin</title>
</svelte:head>
<div class=" text-gray-400 space-y-10 grid lg:grid-cols-2 p-5 lg:w-3/4 mx-auto">
    <form class="space-y-4 md:py-8 mt-8 md:mt-32 p-4">
        <div class="relative">
            <label for="name" class="leading-7 text-sm">Name</label>
            <input
                type="text"
                id="name"
                name="name"
                class="w-full border-b border-gray-400 bg-transparent text-base outline-none py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
            />
        </div>
        <div class="relative">
            <label for="email" class="leading-7 text-sm">Email</label>
            <input
                type="email"
                id="email"
                name="email"
                class="w-full border-b border-gray-400 bg-transparent text-base outline-none py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
            />
        </div>
        <div class="relative">
            <label for="message" class="leading-7 text-sm">Message</label>
            <textarea
                id="message"
                name="message"
                class="w-full border-b border-gray-400 bg-transparent h-32 text-base outline-none py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"
            />
        </div>
        <div>
            <button class="text-gray-400 border-b border-gray-400"
                >Submit</button
            >
        </div>
        <SocialIcons />
    </form>
</div>

// src/pages/contact.tsx
import React from 'react';

const Contact: React.FC = () => {
    return (
        <div className="bg-gray-900 min-h-screen p-10">
            <h1 className="text-white text-4xl font-bold mb-6 sm:text-5xl text-center">Contact Us</h1>
            <form className="bg-white p-6 rounded-lg shadow-xl sm:w-2/3 sm:mx-auto">
                <div className="mb-4">
                    <label className="block text-gray-700 font-bold mb-2" htmlFor="name">
                        Name
                    </label>
                    <input
                        className="w-full border border-gray-400 px-4 py-2 rounded-full outline-none"
                        type="text"
                        id="name"
                        name="name"
                        required
                    />
                </div>
                <div className="mb-4">
                    <label className="block text-gray-700 font-bold mb-2" htmlFor="email">
                        Email
                    </label>
                    <input
                        className="w-full border border-gray-400 px-4 py-2 rounded-full outline-none"
                        type="email"
                        id="email"
                        name="email"
                        required
                    />
                </div>
                <div className="mb-4">
                    <label className="block text-gray-700 font-bold mb-2" htmlFor="message">
                        Message
                    </label>
                    <textarea
                        className="w-full border border-gray-400 px-4 py-2 rounded-xl outline-none"
                        id="message"
                        name="message"
                        rows={5}
                        required
                    />
                </div>
                <button
                    className="bg-orange-500 w-full text-white py-2 px-4 rounded-full hover:bg-orange-600"
                    type="submit"
                >
                    Submit
                </button>
            </form>
        </div>
    );
};

export default Contact;
